"""
Tests for tools/update-index.sh — runs the real script (copied byte-for-byte
into an isolated temp WORKDIR, since the script derives WORKDIR from its own
script path via dirname($0), not from cwd) against fixture jobs/ trees.
"""
import re
import shutil

from helpers import run

HEADER_RE = re.compile(r"^# Auto-generated by tools/update-index\.sh — \d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}Z$")


def _setup_workdir(tmp_path, repo_root):
    tools_dir = tmp_path / "tools"
    tools_dir.mkdir()
    shutil.copy(repo_root / "tools" / "update-index.sh", tools_dir / "update-index.sh")
    (tmp_path / "jobs").mkdir()
    return tmp_path


def test_normal_case_generates_expected_index(tmp_path, repo_root, fixtures_dir):
    workdir = _setup_workdir(tmp_path, repo_root)
    shutil.copytree(fixtures_dir / "update_index" / "job-a", workdir / "jobs" / "job-a")
    shutil.copytree(fixtures_dir / "update_index" / "job-b", workdir / "jobs" / "job-b")
    shutil.copytree(fixtures_dir / "update_index" / "no-meta", workdir / "jobs" / "no-meta")
    shutil.copytree(fixtures_dir / "update_index" / ".hidden", workdir / "jobs" / ".hidden")

    result = run(["bash", str(workdir / "tools" / "update-index.sh")], cwd=workdir)

    assert result.returncode == 0
    assert "Index updated: 2 job(s)" in result.stdout

    index_path = workdir / "jobs" / "index.yaml"
    assert index_path.is_file()
    lines = index_path.read_text().splitlines()

    assert HEADER_RE.match(lines[0])
    expected_body = [
        "jobs:",
        '  - id: "job-a"',
        '    level: "capability"',
        '    status: "done"',
        '    parent: "job-root"',
        '    target_repo: "cic-mcp-test"',
        '    capability_id: "cic_mcp.test.a"',
        '    created: "2026-01-01T00:00:00Z"',
        '    started: "2026-01-01T01:00:00Z"',
        '    completed: "2026-01-01T02:00:00Z"',
        '  - id: "job-b"',
        '    level: "orchestrator"',
        '    status: "pending"',
        '    created: "2026-01-02T00:00:00Z"',
    ]
    assert lines[1:] == expected_body
    # no-meta (no meta.yaml) and .hidden (dotdir) must both be skipped
    assert "hidden-job" not in index_path.read_text()


def test_empty_jobs_dir_produces_jobs_empty_list(tmp_path, repo_root):
    workdir = _setup_workdir(tmp_path, repo_root)

    result = run(["bash", str(workdir / "tools" / "update-index.sh")], cwd=workdir)

    assert result.returncode == 0
    assert "Index updated: 0 job(s)" in result.stdout

    index_path = workdir / "jobs" / "index.yaml"
    lines = index_path.read_text().splitlines()
    assert HEADER_RE.match(lines[0])
    assert lines[1:] == ["jobs: []"]
