#!/usr/bin/env bash
# Generates jobs/index.yaml from all jobs/*/meta.yaml files
set -euo pipefail

WORKDIR="$(cd "$(dirname "$0")/.." && pwd)"

python3 - "$WORKDIR" <<'EOF'
import os, sys
import yaml
from datetime import datetime, timezone

workdir = sys.argv[1]
jobs_dir = os.path.join(workdir, "jobs")

jobs = []
for entry in sorted(os.listdir(jobs_dir)):
    if entry.startswith("."):
        continue
    meta_path = os.path.join(jobs_dir, entry, "meta.yaml")
    if not os.path.isfile(meta_path):
        continue
    with open(meta_path) as f:
        data = yaml.safe_load(f) or {}

    capability = data.get("capability") or {}
    timestamps = data.get("timestamps") or {}

    jobs.append({
        "id":            data.get("job_id", ""),
        "level":         data.get("level", ""),
        "status":        data.get("status", ""),
        "parent":        data.get("parent_job_id", ""),
        "capability_id": capability.get("id", ""),
        "target_repo":   capability.get("target_repo", ""),
        "created":       timestamps.get("created", ""),
        "started":       timestamps.get("started", ""),
        "completed":     timestamps.get("completed", ""),
    })

now = datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")
lines = [f"# Auto-generated by tools/update-index.sh — {now}", "jobs:"]
for j in jobs:
    lines.append(f"  - id: \"{j['id']}\"")
    lines.append(f"    level: \"{j['level']}\"")
    lines.append(f"    status: \"{j['status']}\"")
    if j["parent"]:
        lines.append(f"    parent: \"{j['parent']}\"")
    if j["target_repo"]:
        lines.append(f"    target_repo: \"{j['target_repo']}\"")
    if j["capability_id"]:
        lines.append(f"    capability_id: \"{j['capability_id']}\"")
    lines.append(f"    created: \"{j['created']}\"")
    if j["started"]:
        lines.append(f"    started: \"{j['started']}\"")
    if j["completed"]:
        lines.append(f"    completed: \"{j['completed']}\"")

index_path = os.path.join(jobs_dir, "index.yaml")
with open(index_path, "w") as f:
    f.write("\n".join(lines) + "\n")
print(f"Index updated: {len(jobs)} job(s)")
EOF
